//
//  ServiceEndpoint.swift
//  Mutadawel
//
//  Created by Appinventiv on 20/03/17.
//  Copyright © 2017 Appinventiv. All rights reserved.
//

import Foundation

//let BASE_URL = "http://devtridder.applaurels.com/public/api/"

//let BASE_URL = "http://stagingtridder.applaurels.com/api/"

//let BASE_URL = "http://34.249.162.54/api/"

let BASE_URL = "http://tridder.net/api/"
let BASE_URL_v2 = "http://tridder.net/api/v2/"

//let BASE_URL = "http://beta.tridder.net/api/"
//let BASE_URL_v2 = "http://beta.tridder.net/api/"

struct EndPoint {
    
    static let signUpURL = "\(BASE_URL)signup"
    static let loginURL = "\(BASE_URL)login"
	static let autoLoginURL = "\(BASE_URL)auto-login"
    static let logoutURL = "\(BASE_URL)logout"
    static let changePasswordURL = "\(BASE_URL)change-password"
    static let getMarketListURL = "\(BASE_URL)market_list"
    static let chooseMarketListURL = "\(BASE_URL)choose-market"
    static let getCurrencyuListURL = "\(BASE_URL)get-currency"
    static let chooseFriendURL = "\(BASE_URL)choose-friend"
    static let unfollowFriendURL = "\(BASE_URL)unfollow"
    static let chooseCurrencyuListURL = "\(BASE_URL)choose-currency"
    static let getStockListURL = "\(BASE_URL)stocklist-by-market"
    static let chooseStockListURL = "\(BASE_URL)choose-stock"
    static let getUserListURL = "\(BASE_URL)peopleList"
    static let editProfileURL = "\(BASE_URL)edit-profile"
    static let forgotPasswordURL = "\(BASE_URL)forgot-password"
    static let followerURL = "\(BASE_URL)follower"
    static let followingURL = "\(BASE_URL)following"
    static let userProfileURL = "\(BASE_URL)user-profile"
    static let myProfileURL = "\(BASE_URL)my-profile"
    static let addForecastURL = "\(BASE_URL)add-forecast"
    static let contactUsURL = "\(BASE_URL)contactus"
    static let supportUsURL = "\(BASE_URL)support"
    static let blocked_usersListURL = "\(BASE_URL)blocked-users"
    static let block_userURL = "\(BASE_URL)block-user"
    static let timeLineURL = "\(BASE_URL)timeline"
    static let unBlock_userURL = "\(BASE_URL)unblock-user"
    static let selectedStockListURL = "\(BASE_URL)stocks-by-user"
    static let selectedCurrencyListURL = "\(BASE_URL)currencies-by-user"
    static let reportPostURL = "\(BASE_URL)report-post"
    static let hidePostURL = "\(BASE_URL)hide-post"
    static let unFollowMarketURL = "\(BASE_URL)unfollow-market"
    static let unFollowStockURL = "\(BASE_URL)unfollow-stock"
    static let followingMarketListURL = "\(BASE_URL)following-market"
    static let postListURL = "\(BASE_URL)post-list"
    static let stockSearchURL = "\(BASE_URL)search-stock"
    static let currencySearchURL = "\(BASE_URL)search-currency"
    static let normalSearchURL = "\(BASE_URL)search"
    static let commentListURL = "\(BASE_URL)comment"
    static let commentURL = "\(BASE_URL)save-comment"
    static let comment_RepplyURL = "\(BASE_URL)save-comment-reply"
    static let priceIndicatorURL = "\(BASE_URL)price-indicator"
	static let pendingForecastListURL = "\(BASE_URL)pending-forecast"
    static let rightForecastListURL = "\(BASE_URL)right-forecast"
    static let wrongForecastListURL = "\(BASE_URL)wrong-forecast"
    static let forecastListURL = "\(BASE_URL)forecast-list"
    static let forecastStatusURL = "\(BASE_URL)forecast-status"
    static let stockPriceURL = "\(BASE_URL)stock-price"
    static let saveTradeURL = "\(BASE_URL)save-trade"
    static let rankingURL = "\(BASE_URL)ranking"
    static let userWalletURL = "\(BASE_URL)user-wallet"
    static let saveLikeURL = "\(BASE_URL)save-like"
    static let myStockListURL = "\(BASE_URL)my-stock-list"
    static let myDonationListURL = "\(BASE_URL)my-donation-list"
    static let makeDonationtURL = "\(BASE_URL)make-donation"
    static let accntNotificatinURL = "\(BASE_URL)account-notification"
    static let donationConfirmationURL = "\(BASE_URL)donation-confirmation"
    static let updateForexURL = "\(BASE_URL)update-forex"
    static let addMoreMoneyURL = "\(BASE_URL)add-money"
    static let closeOrderURL = "\(BASE_URL)close-order"
    static let notificationListURL = "\(BASE_URL)notification-list"
    static let profitLossListURL = "\(BASE_URL)profit-loss-list"
    static let sharePostURL = "\(BASE_URL)share-post"
    static let bankDetailURL = "\(BASE_URL)bank-detail"
    static let postDetailURL = "\(BASE_URL)forecast-detail"
    static let likersListURL = "\(BASE_URL)liker-list"
    static let staticPagesURL = "\(BASE_URL)content"
    static let userChatURL = "\(BASE_URL)user-chat"
    static let chatNotificationURL = "\(BASE_URL)chat-notification"
    static let muteUserNotificationURL = "\(BASE_URL)mute-user"
    static let getBankDetailURL = "\(BASE_URL)get-bank-detail"
    static let payPalDetailURL = "\(BASE_URL)paypal-detail"
    static let getPayPalDetailURL = "\(BASE_URL)get-paypal-detail"
    static let feedbackURL = "\(BASE_URL)feedback-list"
    static let saveFeedbackURL = "\(BASE_URL)feedback-save"
    static let readNotificationURL = "\(BASE_URL)update-badge"
    static let setLangURL = "\(BASE_URL)set-language"
	static let getForecastPercentageURL = "\(BASE_URL)forecast-limit"
	static let clickRankingURL = "\(BASE_URL)click-ranking"
	static let priceIndicatorListURL = "\(BASE_URL)price-indicator-list"
	static let walletNetValueURL = "\(BASE_URL_v2)user-stock-data"
    static let boughtStockListURL = "\(BASE_URL)bought-stock-list"
    static let soldStockListURL = "\(BASE_URL)sold-stock-list"
    static let messageClickURL = "\(BASE_URL)message-icon-click"

}
